# Example: Connect to the Master on the secure port 6443
#          MASTER_IP=192.168.122.5:6443
#
MASTER_IP="${MASTER_IP:-10.0.123.15:6443}"
MASTER_NAME="${MASTER_NAME:-master}"

NUM_NODES="${NUM_NODES:-100}"

TEST_CLUSTER_API_CONTENT_TYPE="${TEST_CLUSTER_API_CONTENT_TYPE:-"--kube-api-content-type=test-cluster=application/vnd.kubernetes.protobuf"}"
KUBELET_TEST_LOG_LEVEL="${KUBELET_TEST_LOG_LEVEL:-"--v=2"}"
KUBEPROXY_TEST_LOG_LEVEL="${KUBEPROXY_TEST_LOG_LEVEL:-"--v=2"}"

LOCAL_KUBECONFIG="${LOCAL_KUBECONFIG:-/root/.kube/config}"

KUBEMARK_KUBECONFIG="${KUBEMARK_KUBECONFIG:-/root/kubemark-kubeconfig}"
KUBEMARK_KUBELET_KUBECONFIG_PATH="${KUBEMARK_KUBELET_KUBECONFIG_PATH:-/root/kubemark-kubeconfig}"
KUBEMARK_KUBEPROXY_KUBECONFIG_PATH="${KUBEMARK_KUBEPROXY_KUBECONFIG_PATH:-/root/kubemark-kubeconfig}"

HOLLOW_KUBELET_TEST_ARGS="${HOLLOW_KUBELET_TEST_ARGS:-}"
HOLLOW_PROXY_TEST_ARGS="${HOLLOW_PROXY_TEST_ARGS:-}"
KUBEMARK_IMAGE_TAG="${KUBEMARK_IMAGE_TAG:-v1.13.4}"
KUBEMARK_IMAGE_REGISTRY="${KUBEMARK_IMAGE_REGISTRY:-registry.cn-beijing.aliyuncs.com/hsxue}"
KUBEMARK_MIG_CONFIG="${KUBEMARK_MIG_CONFIG:-}"